spring:
  application:
    name: api-graphql-store
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:mem:store
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
